name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v0.1.0, v1.0.0, etc.
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build Windows executable
      run: |
        pyinstaller rixs_toolbox.spec
    
    - name: Create Windows installer (optional)
      if: false  # Set to true if you want to create NSIS installer
      run: |
        # Install NSIS
        choco install nsis -y
        # Build installer
        makensis installer_windows.nsi
    
    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v3
      with:
        name: windows-build
        path: |
          dist/RIXS_Preparation_Toolbox/
        retention-days: 30

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Build macOS app
      run: |
        pyinstaller rixs_toolbox.spec
    
    - name: Create DMG
      run: |
        mkdir -p dist/dmg_contents
        cp -R "dist/RIXS Preparation Toolbox.app" dist/dmg_contents/
        ln -sf /Applications dist/dmg_contents/Applications
        hdiutil create -volname "RIXS Preparation Toolbox" \
                       -srcfolder dist/dmg_contents \
                       -ov -format UDZO \
                       "dist/RIXS_Preparation_Toolbox_${{ github.ref_name }}.dmg"
    
    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macos-build
        path: |
          dist/RIXS_Preparation_Toolbox*.dmg
        retention-days: 30

  create-release:
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Windows artifacts
      uses: actions/download-artifact@v3
      with:
        name: windows-build
        path: windows-build/
    
    - name: Download macOS artifacts
      uses: actions/download-artifact@v3
      with:
        name: macos-build
        path: macos-build/
    
    - name: Create Windows ZIP
      run: |
        cd windows-build
        zip -r ../RIXS_Preparation_Toolbox_Windows_${{ github.ref_name }}.zip *
        cd ..
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          RIXS_Preparation_Toolbox_Windows_${{ github.ref_name }}.zip
          macos-build/RIXS_Preparation_Toolbox*.dmg
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
